### ISSUE TITLE
how to use 3d image in this code

### ISSUE THREAD

**Issue by FredJChang** [agaldran/balanced_mixup#4]
I want to use the 3D data in this code,and how to modify the code? It just allow PIL image,and I have the type of (24，512，512) 3D Grey Scale Image.

**Comment by agaldran** [comment]
Well, yes, the code was used with RGB images, if you want to use 3d data you need to modify the dataloaders. You will need to change [this line](https://github.com/agaldran/balanced_mixup/blob/c9e053b95c2400a6c33e3cc1c0b405c37595147c/utils/get_loaders.py#L73) and read your images with another library, different than PIL, which can handle 3d inputs.

But that should not affect the rest of the code; the idea is that you sample one bach from each of two loaders, a standard one and a class-balanced one, and the you mixup on those two batches. The data being 3d is not related to this, I would say.

**Comment by FredJChang** [comment]
Sorry, do you mean that it is not easy to use 3d data in this code?  I think it will affect lots of code. Maybe I should read the code carefully again.

**Comment by agaldran** [comment]
What I mean is that I believe it should be easy to adapt the code to 3d, as long as the idea of MixUp works in your 3d-problem. What is implemented here is: 

1) Create a normal dataloader.
2) Create a dataloader that samples data inversely to class frequency.
3) During training, sample one batch from each loader and use mixup on them.

If you do not understand why this is valid for 2d and 3d, I would advice you to look up how mixup works, there must be tons of tutorials online I think. It is also explained in the associated paper, if you want to have a look.

I am closing this issue, but feel free to reopen if you have any other doubt.

Cheers,

Adrian

**Comment by FredJChang** [comment]
Thanks a lot
